apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
  - default:
      cpu: {{ .Values.limits.defaultCpu | quote }}
      memory: {{ .Values.limits.defaultMemory | quote }}
    defaultRequest:
      cpu: {{ .Values.limits.defaultRequestCpu | quote }}
      memory: {{ .Values.limits.defaultRequestMemory | quote }}
    type: Container