apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpuRequests | quote }}
    limits.cpu: {{ .Values.quota.cpuLimits | quote }}
    requests.memory: {{ .Values.quota.memoryRequests | quote }}
    limits.memory: {{ .Values.quota.memoryLimits | quote }}