---
# Binding for Admins
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namespace }}-admin-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: Group
  name: {{ .Values.rbac.adminGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# Binding for Viewers
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namespace }}-view-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: Group
  name: {{ .Values.rbac.viewGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io